const basePath = 'https://codefergog.tk';

export const categories = [
  {
    categoryName: 'Action (set A)',
    imageSrc: `${basePath}/cry.jpg`,
    uniqueKey: '1',
  },
  {
    categoryName: 'Action (set B)',
    imageSrc: `${basePath}/point.jpg`,
    uniqueKey: '2',
  },
  {
    categoryName: 'Animal (set A)',
    imageSrc: `${basePath}/cat.jpg`,
    uniqueKey: '3',
  },
  {
    categoryName: 'Action (set B)',
    imageSrc: `${basePath}/chicken.jpg`,
    uniqueKey: '4',
  },
  {
    categoryName: 'Clothes',
    imageSrc: `${basePath}/fish.jpg`,
    uniqueKey: '5',
  },
  {
    categoryName: 'Emotions',
    imageSrc: `${basePath}/fly.jpg`,
    uniqueKey: '6',
  },
  {
    categoryName: 'Berries',
    imageSrc: `${basePath}/hug.jpg`,
    uniqueKey: '7',
  },
  {
    categoryName: 'Furniture',
    imageSrc: `${basePath}/jump.jpg`,
    uniqueKey: '8',
  },
];

export const cards = [
  [
    {
      word: 'cry',
      translation: 'плакать',
      imageSrc: `${basePath}/cry.jpg`,
      audioSrc: `${basePath}/cry.wav`,
    },
    {
      word: 'dance',
      translation: 'танцевать',
      imageSrc: `${basePath}/dance.jpg`,
      audioSrc: `${basePath}/dance.wav`,
    },
    {
      word: 'dive',
      translation: 'нырять',
      imageSrc: `${basePath}/dive.jpg`,
      audioSrc: `${basePath}/dive.wav`,
    },
    {
      word: 'draw',
      translation: 'рисовать',
      imageSrc: `${basePath}/draw.jpg`,
      audioSrc: `${basePath}/draw.wav`,
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      imageSrc: `${basePath}/fish.jpg`,
      audioSrc: `${basePath}/fish.wav`,
    },
    {
      word: 'fly',
      translation: 'летать',
      imageSrc: `${basePath}/fly.jpg`,
      audioSrc: `${basePath}/fly.wav`,
    },
    {
      word: 'hug',
      translation: 'обнимать',
      imageSrc: `${basePath}/hug.jpg`,
      audioSrc: `${basePath}/hug.wav`,
    },
    {
      word: 'jump',
      translation: 'прыгать',
      imageSrc: `${basePath}/jump.jpg`,
      audioSrc: `${basePath}/jump.wav`,
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      imageSrc: `${basePath}/open.jpg`,
      audioSrc: `${basePath}/open.wav`,
    },
    {
      word: 'play',
      translation: 'играть',
      imageSrc: `${basePath}/play.jpg`,
      audioSrc: `${basePath}/play.wav`,
    },
    {
      word: 'point',
      translation: 'указывать',
      imageSrc: `${basePath}/point.jpg`,
      audioSrc: `${basePath}/point.wav`,
    },
    {
      word: 'ride',
      translation: 'ездить',
      imageSrc: `${basePath}/ride.jpg`,
      audioSrc: `${basePath}/ride.wav`,
    },
    {
      word: 'run',
      translation: 'бегать',
      imageSrc: `${basePath}/run.jpg`,
      audioSrc: `${basePath}/run.wav`,
    },
    {
      word: 'sing',
      translation: 'петь',
      imageSrc: `${basePath}/sing.jpg`,
      audioSrc: `${basePath}/sing.wav`,
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      imageSrc: `${basePath}/skip.jpg`,
      audioSrc: `${basePath}/skip.wav`,
    },
    {
      word: 'swim',
      translation: 'плавать',
      imageSrc: `${basePath}/swim.jpg`,
      audioSrc: `${basePath}/swim.wav`,
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      imageSrc: `${basePath}/cat.jpg`,
      audioSrc: `${basePath}/cat.wav`,
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      imageSrc: `${basePath}/chick.jpg`,
      audioSrc: `${basePath}/chick.wav`,
    },
    {
      word: 'chicken',
      translation: 'курица',
      imageSrc: `${basePath}/chicken.jpg`,
      audioSrc: `${basePath}/chicken.wav`,
    },
    {
      word: 'dog',
      translation: 'собака',
      imageSrc: `${basePath}/dog.jpg`,
      audioSrc: `${basePath}/dog.wav`,
    },
    {
      word: 'horse',
      translation: 'лошадь',
      imageSrc: `${basePath}/horse.jpg`,
      audioSrc: `${basePath}/horse.wav`,
    },
    {
      word: 'pig',
      translation: 'свинья',
      imageSrc: `${basePath}/pig.jpg`,
      audioSrc: `${basePath}/pig.wav`,
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      imageSrc: `${basePath}/rabbit.jpg`,
      audioSrc: `${basePath}/rabbit.wav`,
    },
    {
      word: 'sheep',
      translation: 'овца',
      imageSrc: `${basePath}/sheep.jpg`,
      audioSrc: `${basePath}/sheep.wav`,
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      imageSrc: `${basePath}/bird.jpg`,
      audioSrc: `${basePath}/bird.wav`,
    },
    {
      word: 'fish',
      translation: 'рыба',
      imageSrc: `${basePath}/fish1.jpg`,
      audioSrc: `${basePath}/fish-a.wav`,
    },
    {
      word: 'frog',
      translation: 'жаба',
      imageSrc: `${basePath}/frog.jpg`,
      audioSrc: `${basePath}/frog.wav`,
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      imageSrc: `${basePath}/giraffe.jpg`,
      audioSrc: `${basePath}/giraffe.wav`,
    },
    {
      word: 'lion',
      translation: 'лев',
      imageSrc: `${basePath}/lion.jpg`,
      audioSrc: `${basePath}/lion.wav`,
    },
    {
      word: 'mouse',
      translation: 'мышь',
      imageSrc: `${basePath}/mouse.jpg`,
      audioSrc: `${basePath}/mouse.wav`,
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      imageSrc: `${basePath}/turtle.jpg`,
      audioSrc: `${basePath}/turtle.wav`,
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      imageSrc: `${basePath}/dolphin.jpg`,
      audioSrc: `${basePath}/dolphin.wav`,
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      imageSrc: `${basePath}/skirt.jpg`,
      audioSrc: `${basePath}/skirt.wav`,
    },
    {
      word: 'pants',
      translation: 'брюки',
      imageSrc: `${basePath}/pants.jpg`,
      audioSrc: `${basePath}/pants.wav`,
    },
    {
      word: 'blouse',
      translation: 'блузка',
      imageSrc: `${basePath}/blouse.jpg`,
      audioSrc: `${basePath}/blouse.wav`,
    },
    {
      word: 'dress',
      translation: 'платье',
      imageSrc: `${basePath}/dress.jpg`,
      audioSrc: `${basePath}/dress.wav`,
    },
    {
      word: 'boot',
      translation: 'ботинок',
      imageSrc: `${basePath}/boot.jpg`,
      audioSrc: `${basePath}/boot.wav`,
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      imageSrc: `${basePath}/shirt.jpg`,
      audioSrc: `${basePath}/shirt.wav`,
    },
    {
      word: 'coat',
      translation: 'пальто',
      imageSrc: `${basePath}/coat.jpg`,
      audioSrc: `${basePath}/coat.wav`,
    },
    {
      word: 'shoe',
      translation: 'туфли',
      imageSrc: `${basePath}/shoe.jpg`,
      audioSrc: `${basePath}/shoe.wav`,
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      imageSrc: `${basePath}/sad.jpg`,
      audioSrc: `${basePath}/sad.wav`,
    },
    {
      word: 'angry',
      translation: 'сердитый',
      imageSrc: `${basePath}/angry.jpg`,
      audioSrc: `${basePath}/angry.wav`,
    },
    {
      word: 'happy',
      translation: 'счастливый',
      imageSrc: `${basePath}/happy.jpg`,
      audioSrc: `${basePath}/happy.wav`,
    },
    {
      word: 'tired',
      translation: 'уставший',
      imageSrc: `${basePath}/tired.jpg`,
      audioSrc: `${basePath}/tired.wav`,
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      imageSrc: `${basePath}/surprised.jpg`,
      audioSrc: `${basePath}/surprised.wav`,
    },
    {
      word: 'scared',
      translation: 'испуганный',
      imageSrc: `${basePath}/scared.jpg`,
      audioSrc: `${basePath}/scared.wav`,
    },
    {
      word: 'smile',
      translation: 'улыбка',
      imageSrc: `${basePath}/smile.jpg`,
      audioSrc: `${basePath}/smile.wav`,
    },
    {
      word: 'laugh',
      translation: 'смех',
      imageSrc: `${basePath}/laugh.jpg`,
      audioSrc: `${basePath}/laugh.wav`,
    },
  ],
  [
    {
      word: 'cranberry',
      translation: 'клюква',
      imageSrc: `${basePath}/cranberry.jpg`,
      audioSrc: `${basePath}/cranberry.wav`,
    },
    {
      word: 'blueberry',
      translation: 'черника',
      imageSrc: `${basePath}/blueberry.jpg`,
      audioSrc: `${basePath}/blueberry.wav`,
    },
    {
      word: 'elderberry',
      translation: 'бузина',
      imageSrc: `${basePath}/elderberry.jpg`,
      audioSrc: `${basePath}/elderberry.wav`,
    },
    {
      word: 'gooseberry',
      translation: 'крыжовник',
      imageSrc: `${basePath}/gooseberry.jpg`,
      audioSrc: `${basePath}/gooseberry.wav`,
    },
    {
      word: 'currant',
      translation: 'клюква',
      imageSrc: `${basePath}/currant.jpg`,
      audioSrc: `${basePath}/currant.wav`,
    },
    {
      word: 'strawberry',
      translation: 'клубника',
      imageSrc: `${basePath}/strawberry.jpg`,
      audioSrc: `${basePath}/strawberry.wav`,
    },
    {
      word: 'blackberry',
      translation: 'ежевика',
      imageSrc: `${basePath}/blackberry.jpg`,
      audioSrc: `${basePath}/blackberry.wav`,
    },
    {
      word: 'physalis',
      translation: 'физалис',
      imageSrc: `${basePath}/physalis.jpg`,
      audioSrc: `${basePath}/physalis.wav`,
    },
  ],
  [
    {
      word: 'bed',
      translation: 'кровать',
      imageSrc: `${basePath}/bed.jpg`,
      audioSrc: `${basePath}/bed.wav`,
    },
    {
      word: 'sofa',
      translation: 'диван',
      imageSrc: `${basePath}/sofa.jpg`,
      audioSrc: `${basePath}/sofa.wav`,
    },
    {
      word: 'carpet',
      translation: 'ковёр',
      imageSrc: `${basePath}/carpet.jpg`,
      audioSrc: `${basePath}/carpet.wav`,
    },
    {
      word: 'chair',
      translation: 'стул',
      imageSrc: `${basePath}/chair.jpg`,
      audioSrc: `${basePath}/chair.wav`,
    },
    {
      word: 'table',
      translation: 'стол',
      imageSrc: `${basePath}/table.jpg`,
      audioSrc: `${basePath}/table.wav`,
    },
    {
      word: 'armchair',
      translation: 'кресло',
      imageSrc: `${basePath}/armchair.jpg`,
      audioSrc: `${basePath}/armchair.wav`,
    },
    {
      word: 'picture',
      translation: 'картина',
      imageSrc: `${basePath}/picture.jpg`,
      audioSrc: `${basePath}/picture.wav`,
    },
    {
      word: 'floor lamp',
      translation: 'напольная лампа',
      imageSrc: `${basePath}/floorlamp.jpg`,
      audioSrc: `${basePath}/floorlamp.wav`,
    },
  ],
];
